### ISSUE TITLE
Add Asynchronous Functionality

### ISSUE THREAD

**Issue by Were-Woof** [WillofSteel-Devs/api-wrapper#3]
Currently, the api-wrapper only has synchronous functionality, largely due to its use of the synchronous ``requests`` library.
![image](https://github.com/user-attachments/assets/41083567-fce4-425f-89f6-91eaba59334d)

Due to the this, the api-wrapper cannot easily be used inside of asynchronous projects - such as apps with a gui, or discord bots - without blocking the rest of the application. Within apps with a gui, this will cause the gui to be unresponsive and provide a poor user experience. Within discord bots, this will prevent the bot from responding to other commands and potentially cause it to disconnect entirely.

To fix this issue, I would like to add an ``AsyncClient`` class. This class would have the same functionality as the ``Client`` class, but rewritten to support asynchronous programming. I would like to use the ``aiohttp`` library in place of ``requests`` to make asynchronous api calls, the documentation for it can be found [here](https://docs.aiohttp.org/en/stable/).

**Comment by ItsNeil17** [comment]
Hey @Were-Woof,

Implementing this was always on our backlog but I could never get around to doing it due to other Will of Steel projects; 
I would suggest making a different task loop to achieve this (this is the only way I think it could be done) but if you have any other ideas, feel free to experiment and shoot me a PR!

**Comment by Were-Woof** [comment]
Hey @ItsNeil17,

Was just wondering what your preference was for implementing ``_verify_key``. I see a few different ways to do it:

1. It could be run synchronously. This would basically mean its only blocking when the client is initialized, this still isn't ideal for the reasons listed at the start of this issue.
2. It could be run using ``asyncio.run()``, however this may cause issues as you can't always use this inside an existing event loop.
3. We can add the task of validating the key to be run to the current event loop. I've shown how this might look below, but the potential issue with this is that depending on the already existing event loop this may never get run if it doesn't pause.
4. We could let the user specify how they would like the key to be validated when they initialize an instance of the class, only decision then would be deciding what the default should be (if we want a default).

```py
class AsyncClient:
    """
    Asynchronous client for the Will of Steel API.

    """

    def __init__(self, api_key: str, logger: LoggingObject = MISSING):
        self.api_key = api_key
        self.headers = {
            "API-Key": self.api_key,
            "User-Agent": "Will of Steel API Wrapper",
            "Accept": "application/json",
            "X-API-Version": "0.3"
        }

        setup_logging(logger if logger else LoggingObject())
        loop = asyncio.get_event_loop()
        loop.create_task(self._verify_key())

    async def _verify_key(self) -> None:
        response = self.request("GET", "/verify", self.headers)
        if response.status == 403:
            raise InvalidKey
        elif response.status == 200:
            logging.info("Key verification successful.")
        else:
            raise ServerError
```

**Comment by ItsNeil17** [comment]
I think the 4th option would be good so that the user can decide what they want to do, but since we're going to have a different AsyncClient, I don't think we need to implement a sync/blocking verification of the API key. 

But the verification of the API key should be done at the very start of the program before any other queries so that we don't encounter other errors afterwards. 

I suggest you can do what you think is best and if something is wrong I'll let you know
